spring:
  application:
    name: spacetraderTest

hibernate:
  ddl-auto: create-drop
  properties:
    hibernate:
      cache:
        use_second_level_cache: false
        use_query_cache: false

logging:
  level:
    org:
      springframework: INFO
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  profiles:
    active: integration
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  token:
    secret: 5pAq6zRyX8bC3dV2wS7gN1mK9jF0hL4tUoP6iBvE3nG8xZaQrY7cW2fA=